Bounties
SolarMC-Dev/DataLoader pull request #23
Opened 2021-04-09 19:33 UTC by Auriium

Gotta merge this quick so i can get back to work on kitpvp

2021-04-09 19:42 UTC, A248 requested changes
Needs a couple of things then can be merged

2021-04-09 19:42 UTC, A248 commented on core-authentication/pom.xml
> +        <plugins>
You committed these everywhere.

2021-04-09 19:42 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +    public void addBounty(Transaction transaction, int amount) {
Needs javadoc

2021-04-09 19:43 UTC, Auriium commented on core-authentication/pom.xml
> +        <plugins>
What?

2021-04-09 19:43 UTC, Auriium commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +    public void addBounty(Transaction transaction, int amount) {
Fine

2021-04-09 19:43 UTC, Auriium commented on core-authentication/pom.xml
> +        <plugins>
Oops

2021-04-09 19:45 UTC, Auriium commented on core-authentication/pom.xml
> +        <plugins>
Im not entirely sure how that happened

2021-04-09 19:52 UTC, Auriium commented
@A248

2021-04-09 20:03 UTC, A248 reviewed
Don't you need a method to get the bounty?

2021-04-09 20:03 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +     * @param transaction transa
```suggestion
     * @param transaction the transaction
```

2021-04-09 20:03 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +     * @param amount amount to add
```suggestion
     * @param amount amount to add
     * @throws IllegalArgumentException if the amount is negative
```

2021-04-09 21:55 UTC, Auriium commented
@A248 merge it i dare you

2021-04-09 21:55 UTC, Auriium commented
FUCK WHYD IT CLOSE

2021-04-11 15:29 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +     * Gets the mounty
```suggestion
     * Gets the bounty
```

2021-04-11 15:29 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +     * @param transaction trans
```suggestion
     * @param transaction the transaction
```

2021-04-11 15:29 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/KitPvp.java
> +     * resets the bounty. infallible.
```suggestion
     * Resets the bounty. infallible.
```

2021-04-11 15:29 UTC, A248 commented on mod-kitpvp/src/main/java/gg/solarmc/loader/kitpvp/OnlineKitPvp.java
> +
```suggestion

    /**
     * The cached bounty value. Not reliable
     * @return the bounty
     */
```

2021-04-11 21:46 UTC, A248 approved these changes

2021-04-11 21:46 UTC, merged